"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const PlaylistController_1 = require("../controller/PlaylistController");
const express_2 = require("@clerk/express");
const UserController_1 = require("../controller/UserController");
const router = express_1.default.Router();
router.use((0, express_2.clerkMiddleware)());
router.use((0, express_2.requireAuth)());
router.use(UserController_1.findOrCreateUser);
router.get("/:playlistId", PlaylistController_1.getPlaylistById);
router.post("/create", PlaylistController_1.createPlaylist);
router.patch("/update/:playlistId", PlaylistController_1.updatePlaylist);
router.post("/:playlistId/videos", PlaylistController_1.addVideoToPlaylist);
router.post("/:playlistId/videos/:videoId", PlaylistController_1.removeVideoFromPlaylist);
router.delete("/delete/:playlistId", PlaylistController_1.deletePlaylist);
exports.default = router;
